<?php
/**
 * Template Name: License Agreement Template
 *
 *
 * @package WordPress
 * @subpackage Twenty_Nineteen
 * @since 1.0.0
 */

get_header();
?>
    <div class="container privacy-pg">
        <section class="l-section">
            <div class="l-section-wrap breadcrumb">
                <ul>
                    <li class="breadcrumb-item"><a href="">Magpplus</a></li>
                    <li class="breadcrumb-item"><a href="">Pricing</a></li>
                </ul>
            </div>
        </section>
        
        <section class="l-section sec-pad white-bg pad-top0">
            <div class="l-section-wrap">
                <div class="sticky-nav-block"> 
                    <ul class="nav sticky-sidebar">
                        <li><a href="?page_id=870" class="nav-link" title="Privacy Policy">Privacy Policy</a></li>
                        <li><a href="?page_id=867" class="nav-link" title="Terms of Use">Terms of Use</a></li>
                        <li class="active"><a href="?page_id=608" class="nav-link" title="License and Agreement">License and Agreement</a></li>
                    </ul>
                </div>
                <div class="content-block">
                    <h3 class="sec-title">License and Agreement</h3> 
                    <span>Last updated: September 29, 2017</span>
                    
                    <p>This is a legally binding agreement between you (either an individual or a single entity, or any organization), referred to herein as “mag+ Customer”, and MPS NA LLC, 50 Main Street, White Plains, New York 10606, USA (d/b/a mag+ ) referred to herein as “mag+” for the Software, SDK (or, as applicable, Trial SDK) identified in the mag+ Customer Order Confirmation, including any applicable Professional Services, and Support.</p>
                    <p>mag+ Customer (as defined in the mag+ Customer Order Confirmation- “Order”) desires to use the Software, Trial SDK, and/or SDK, as agreed in the Order and to receive, to the extent applicable, certain services from mag+, in connection with publishing Apps for deployment via Marketplace(s) on Target Devices. The general terms and conditions contained in this mag+ Customer End User License Agreement (“EULA”) and the Order regulate the relationship between mag+ and mag+ Customer in connection with this Agreement.</p>
                    <p>Terms of usage in this Agreement may be defined in this EULA or in the Order.</p>
                    <p>By downloading, installing, copying, accessing or using this software, mag+ Customer agrees to be bound by the terms of this EULA, the Order, and the Conditions of Use and Privacy Policy posted on <a href="www.magplus.com/legal" class="text-link">www.magplus.com/legal</a>.</p>
                    <p>If mag+ Customer does not agree to the terms of this EULA, the Order, the Conditions of Use and Privacy Policy, mag+ Customer is prohibited from downloading, installing, accessing, copying or using the Software, SDK, and/or Trial SDK.</p>
                     <p>
                        <strong>1. GENERAL TERMS AND CONDITIONS</strong>
                        <b>"Agreement"</b> means the combination of the mag+ Customer Order Confirmation and this EULA and/or links referring to this EULA
                        <br/><br/><b>"App"</b> means mag+ Customer’s digital app, which renders mag+ Customer’s content (MIB file), e.g. a digital Magazine, a book, a brochure, an annual report, or other set of content directly owned by  Company for every country of circulation—created (in whole or in part) as a result of using the Software and/or SDK.
                        <br/><br/><b>"Business Days"</b> means normal working days (excluding weekends and holidays)
                        <br/><br/><b>"Deliverable"</b> means any deliverable(s), identified in any writing agreed to by the parties concerning Professional Services that mag+ provides to mag+ Customer.
                        <br/><br/><b>"Derivatives"</b> means (a) for copyrighted or copyrightable material, any abridgment, revision, translation, enhancement, improvement, modification, expansion, compilation or other form in which an existing work may be recast, transformed or adapted, (b) for patented or patentable material, any improvement thereof, or (c) for trade secrets, any new material derived from such existing trade secret material, including new material which may be protected by copyright, patent or trade secret.
                        <br/><br/><b>"Documentation"</b> means any documentation in electronic or hard-copy form, any present and future manuals, instructions, user guides and any other materials related to Software, SDK, or Trial SDK provided by mag+ under the Agreement.
                        <br/><br/><b>"Effective Date"</b> is the date of the last signature on the Order or if the Order is placed electronically, the date of Order confirmation by mag+.
                        <br/><br/><b>"Independent Contractors"</b> means any third party company used by mag+ or mag+ Customer in connection with this Agreement.
                        <br/><br/><b>"IPR"</b> means any and all now or hereafter known tangible and/or intangible: (a) right associated with works of authorship throughout the world, including but not limited to, copyrights, moral rights, and mask works; (b) trademarks and trade name rights and similar rights, throughout the world; (c) trade secret and know-how rights throughout the world; (d) patents, designs, algorithms, and other intellectual and/or industrial property rights including mag+ Designd Plugin, mag+ Production Tool, mag+ Reviewer App, and mag+ Publish Portal(of every kind and nature throughout the world and however designated) whether arising by operation of law, contract, license or otherwise; (e) all registrations, initial applications, renewals, extensions, continuations, divisions or re-issues thereof now or hereafter in force; and (f) Derivatives.
                        <br/><br/><b>"Issue"</b>  means MIB file published to its respective App. Each time any changes and/or corrections to the MIB file are published to the App, a new Issue of such App is created.
                        <br/><br/><b>"Login"</b> provided in the mag+ Designd plugin is used to carry out usage analytics of the plugin. There is no purchase required for using the Designd Plugin. mag+ Publish Portal Login requires purchase of License to access and use the set of features and other custom services in Publish portal
                        <br/><br/><b>"End User License Agreement"</b> or <b>"EULA"</b> means these general terms and conditions for Software, SDK, and Trial SDK, including any appendices hereto.
                        <br/><br/><b>"mag+ Customer Order Confirmation"</b> or “Order” means the mag+ Customer order setting forth the details of the order as well as the payment terms for the Subscription, SDK, and/or Trial SDK, as well as, if applicable, Priority Support, Professional Services, and any add-ons, which is either (i) signed by mag+ Customer, (ii) accepted by mag+ Customer via the Magplus.com ordering interface, and/or appended to this Agreement according to the terms herein.
                        <br/><br/><b>"Marketplace"</b>  means the specific digital distribution marketplace(s) via which mag+ Customer distributes its App(s). Such Marketplaces may include iTunes, GooglePlay, Amazon, and mag+ Customer’s internal distribution network (such as, Intranet).
                        <br/><br/><b>"MIB"</b> means the mag+ Issue Bundle file format providing the structure and allowing access to digital App content. The MIB is part of the Software and is generated by the mag+ Plug-in which itself constitutes part of the Software.
                        <br/><br/><b>"Professional Services"</b> means any services provided by mag+ in connection with this agreement and in accordance with APPENDIX A which are not expressly included in Support Services
                        <br/><br/><b>"Registered User"</b> means each mag+ Customer employee or Independent Contractor legally permitted to use the Software, and/or SDK or Trial SDK according to the terms of this Agreement.
                        <br/><br/><b>"SDK"</b> means the mag+ Software development kit, which, if included in the Order, and subject to the pricing set forth therein, can be utilized by mag+ Customer according to the terms of this Agreement.
                        <br/><br/><b>"Software"</b> means the mag+ Software programs (including, without limitation, the mag+ Plugin, mag+ Publish, mag+ Reviewer App and MIB files), protected by copyright laws and international copyright treaties, provided by mag+ under this Agreement.
                        <br/><br/><b>"Specifications"</b> means the specifications for Software (i.e. applicable to the Software Subscription(s) set forth in the Order and/or in this EULA) as well as, to the extent applicable to this Agreement, the SDK or Trial SDK, as set forth in the Agreement.
                        <br/><br/><b>"Subscription"</b> means each license or service subscription selected in the respective Order.
                        <br/><br/><b>"Target Device(s)</b> means the range of mobile media devices referenced at https://support.Magplus.com/entries/22274861, as updated from time to time by mag+.
                        <br/><br/><b>"Trial SDK"</b> means the mag+ Software development kit, which, if included in the Order, and subject to the pricing set forth therein or as subsequently charged by mag+, can be utilized by mag+ Customer solely for non-commercial purposes, according to the terms of this Agreement.
                        <br/><br/><b>"Updates"</b> means any and all updates, fixes, patches, and modifications (excluding modifications performed by mag+ as Professional Services) of the Software, SDK, Trial SDK  and Documentation
                        <br/><br/><b>"Upgrades"</b> means any and all new releases of the Software, SDK or Trial SDK containing functional improvement. Upgrades, if furnished to mag+ Customer, are included within the definition of Software (or, as applicable, Trial SDK or SDK) for purposes of this Agreement.
                     </p>   
                     <p>
                         <strong>2. SCOPE OF AGREEMENT</strong>
                         In the event of any inconsistency between the Order and this EULA, the Order shall prevail if a clear statement is provided therein of the intention for the EULA to be superseded on the particular issue. In addition, should mag+ Customer be placing an order online at magplus.com, billing and payment timing as well as product speciﬁcations and limitations may be clariﬁed on such website and any such clariﬁcations which are inconsistent with the terms of this EULA shall prevail over this EULA – with regard to billing, invoicing, and product speciﬁcations / limitations. With the foregoing said, any such representations or statements made on the magplus.com website shall in no manner be construed to limit the terms and conditions of Section 8 & Section 9 of this EULA. mag+ Customers ordering online assume the responsibility of ensuring a full review of all applicable terms and conditions appearing online at the magplus.com website in connection with the purchase in question and, by accepting the terms of this EULA thereby accept the terms and conditions stated online at magplus.com in connection with any and all purchases.
                     </p>   
                     <p>
                        <strong>3. Limited license</strong>
                        3.1 Subject to the terms and conditions of this Agreement and subject to any limitations set forth in the Order (in connection with the Subscription selected therein), mag+ grants mag+ Customer the non-exclusive, non-transferable, time-limited, fee-based rights and licenses (without the right to sublicense) to:<br/><br/>
                        a) Have each Registered User use the Software, Documentation, and Deliverables in connection with developing, deploying, and distributing, via Marketplaces, App(s) on or through Target Device(s).<br/><br/>
                        b) Make copies of Software, Deliverables, and Documentation as required to exercise the license grant in this Section 2.1 and for back-up purposes, provided any copyright notices and/or proprietary legends contained therein remain intact.<br/><br/>
                        3.2 Subject to the terms and conditions of this Agreement, mag+ grants mag+ Customer, in connection with the SDK (if SDK is included under this Agreement), the non-exclusive, non-transferable, time-limited, fee-based rights and licenses (without the right to sublicense) to have each Registered User use the SDK in connection with developing an App that reads a MIB or otherwise utilizes any component of the Software (including mag+ Publish or mag+ Plug-in) to be used in connection with the Software in furtherance of mag+ Customer’s publication of Apps according to the applicable Subscription package set forth in the mag+ Customer Order Confirmation. mag+ Customer shall, however, at no time use the SDK or any results of its use of the SDK to compete with mag+ or to develop any results to be used in connection with any software other than the Software. The terms and conditions of the SDK shall apply equally to the Trial SDK to the extent not stated otherwise in this Agreement. The Trial SDK term shall be for thirty (30) calendar days and shall, at no time, permit commercial use of the results thereof unless and until mag+ Customer has licensed and paid for its license to the SDK.<br/><br/>
                        3.3 mag+ reserves the right (but shall have no obligation) to remove any or all content from the mag+ Software and/or related services in the event such content, in mag+’s reasonable assessment, exposes mag+ to any potential third party or governmental claims, including, without limitation, IPR infringement claims (“Content Claims”). mag+ Customer agrees to immediately remove any content that (i) may give rise to Content Claims or (ii) mag+ has requested be removed. Further, mag+ Customer shall indemnify, defend, and hold mag+ harmless from and against any Content Claims.
                     </p>   
                     <p>
                         <strong>4. Confidentiality</strong>
                         4.1 Each party agrees that it shall not disclose to any third party any information concerning the customers, trade secrets, methods, processes or procedures or any other confidential, financial or business information of the other party which it learns during the course of its performance of this EULA, without the prior written consent of such other party. This obligation shall survive the cancellation or other termination of this EULA. The Software, SDK OR Trial SDK contains trade secrets and proprietary know-how that belong to mag+ and it is being made available to mag+ Customer  in strict confidence. ANY USE OR DISCLOSURE OF THE SOFTWARE, OR OF ITS ALGORITHMS, PROTOCOLS OR INTERFACES, OTHER THAN IN STRICT ACCORDANCE WITH THIS EULA, MAY BE ACTIONABLE AS A VIOLATION OF mag+’s TRADE SECRET RIGHTS.<br><br>
                         4.2 Each party may use Independent Contractors to exercise its rights and/or fulfil its obligations under this Agreement. Any Independent Contractor’s breach of the terms of this Agreement shall be treated as if being a breach by the party that retained such Independent Contractor. All material concerning Software, SDK, Trial SDK, Deliverable(s), and Documentation shall be returned to mag+ Customer when the work has been completed by its Independent Contractor(s). Any Independent Contractor retained by the mag+ customer shall also be governed by the terms and conditions of this Agreement.
                     </p>   
                     <p>
                        <strong>5. Proprietary rights</strong>
                        <p>mag+ shall retain and acquire all rights, title, and interest, including, without limitation, IPR, recognized anywhere in the world, to the Software, SDK, Trial SDK, Documentation, Deliverables, Support, add-ons, and any Derivatives of any of the foregoing. Deliverables are licensed to mag+ Customer on the same terms and conditions as the Software as set forth in this Agreement. mag+ Customer hereby assigns to mag+ (and warrants and represents mag+ Customer’s Independent Contractor(s) shall have assigned to mag+ Customer) all rights, title, and interests in and to the Software, SDK, Trial SDK, , Documentation, and Deliverables (including, without limitation, IPR) as necessary to give full legal effect to this Section. mag+ Customer agrees to take all actions required and/or otherwise reasonably requested by mag+ to secure and protect IPR assigned to mag+. For the avoidance of doubt, mag+ Customer reserves all rights in relation to mag+ Customer’s content supplied to mag+ for purpose of mag+ performing its obligations under this Agreement. All of mag+ Customer’s rights which are not specifically granted to mag+ (to the extent not containing mag+ IPR) are reserved to mag+ Customer.</p>
                     </p>   
                     <p>
                        <strong>6. General Restrictions</strong>
                        mag+ Customer may not, and may not cause or allow any third party to:
                        <br/><br/>(i) modify or create any derivative works of the Software or documentation, including customization, any modifications or enhancements, translation or localization without mag+ express written consent;
                        <br/><br/>(ii) reverse engineer, decompile, disassemble, make or otherwise attempt to derive the source code of the Software, or the underlying ideas or algorithms of the Software;
                        <br/><br/>(iii) attempt to gain unauthorized access to Documents, mag+ servers or any other service, account, computer system or network associated with the Software or with mag+, it’s affiliates, agents, partners and customers;
                        <br/><br/>(iv) remove or alter any trademark, logo, copyright or other proprietary notices or symbols in the Software;
                        <br/><br/>(v) block, disable, or otherwise affect any advertising, banner window, tab, link to websites and services, or other features that are part of the Software;
                        <br/><br/>(vi) incorporate, integrate or otherwise include the Software or any portion thereof into any software, program or product;
                        <br/><br/>(vii) provide false information when registering the Software;
                        <br/><br/>(viii) digitally transmit or make available the Software or its content through local networks, intranets, extranets, FTP, online discussion boards, forums, list-serve, peer-to-peer networks or technologies, newsgroups, bulletin boards, or any other mode of shared communication system, or place the Software onto a server so that it is accessible via a pubic network such as the Internet;
                        <br/><br/>(ix) use the Software in any way that violates this EULA or any law;
                        <br/><br/>(x) publish any performance or benchmark tests or analysis relating to software
                        <br/><br/>(xi) In no event shall mag+ Customer (directly or indirectly) use the Software, SDK, Trial SDK and/or Deliverable(s) for mag+ Customer’s development (directly or indirectly) of any product(s) and/or service(s) competing (directly or indirectly) with mag+.
                        <br/><br/>(xii) In addition to the terms of this Agreement, mag+ Customer may not use or otherwise export or re-export the Software in any manner violative of the laws of the United States, the laws of the jurisdiction in which the Software was obtained, as well as the laws of any other country which are applicable to this Agreement.
                     </p>   
                     <p>
                        <strong>7. Fees</strong>
                        7.1 The applicable fee(s) are set forth in the Order in relation to the Software Subscription, SDK, and/or Trial SDK selected by mag+ Customer as well as any Professional Services, Priority Support, add-ons in connection therewith. To the extent any additional Issue(s), App(s), Professional Services, Priority Support, add-ons are incorporated by mag+ Customer into this Agreement after the Effective Date, the terms of the Order shall apply subject to annual pricing increases by mag+ and only as otherwise agreed in writing by the parties to this Agreement.
                        <br/><br/>7.2 mag+ Customer shall remit payment in accordance with the terms of the Order or as otherwise agreed to in writing by and between the parties. Any breach of this Section 7 shall be a material breach of this Agreement.
                        <br/><br/>7.3 All Payment obligations are irrevocable once taking effect and all amounts paid are non-refundable 7.4 All fees shall be paid in United States Dollar (USD) to MPS North America LLC exclusive of any expenses, costs, taxes, duties, and/or customs of any kind (as any and all such assessments shall be in addition to such fees).
                        <br/><br/>7.5 mag+ may securely share mag+ Customer’s credit card information with third parties as necessary for standard payment processing. Further, to the extent any recurring or further fees (including, but not limited to, Hosting) shall be subsequently applied in connection with any purchase, such subsequent payments shall be applied to the same payment method (e.g. credit card, Wire transfer or ACH, etc.) that was used for the immediately preceding applied charges—unless mag+ Customer has informed the mag+ billing department otherwise, in writing.
                        <br/><br/>7.6 Should mag+ Customer be legally required to withhold income-related taxes based on mag+ Customer’s payments to mag+, mag+ Customer shall timely remit any such withheld amounts to the appropriate tax authority and shall promptly provide mag+ with any and all assistance necessary for mag+ to obtain any tax credit available to mag+. mag+ Customer shall indemnify mag+ for any and all costs (including, without limitation, legal, accountancy fees, and any penalties) incurred in connection with mag+ Customer’s breach of the terms of this Section.
                        <br/><br/>7.7 Any delinquent payments shall accrue penalty interest at the rate of two percent (2%) per commenced month of delay. Further, mag+ Customer shall indemnify mag+ for all costs (including, without limitation, attorneys’ fees and collections costs) incurred in connection with recovering any and all amounts due and owing, pursuant to the terms of this Agreement, from mag+ Customer to mag+.
                        <br/><br/>7.8 Support, to the extent applicable, shall commence upon the Effective Date of the Order and shall terminate upon, as applicable, the expiration or termination of the Subscription, SDK, and/or Trial SDK term to which such Support relates. mag+ shall continue to make Support available on the current release & the immediately preceeding release of the Software, SDK, and Trial SDK during the term of the Agreement. For older releases, applicable Professional Service rates shall apply unless otherwise agreed in writing.
                        <br/><br/>7.9 Professional Service rates, subject to annual increase, are as set forth in the Order and shall be invoiced upon the date agreed to, in writing, by and between the Parties hereto. If nothing is stated otherwise in the Order or otherwise in writing signed by mag+, the invoice shall be issued monthly in arrears and shall be paid within thirty (30) calendar days from the date of invoice.
                     </p>   
                     <p>
                        <strong>8. WARRANTY DISCLAIMER</strong>
                        8.1 mag+ warrants that, to the best of its knowledge, the Software and, to the extent included in this Agreement, the SDK and/or Trial SDK, solely in their unmodified form, do not infringe any third party’s copyright(s), trade secret(s), or patent(s) granted as of the Effective Date.
                        <br/><br/>8.2 mag+ warrants the Software and, to the extent included in this Agreement, the SDK and/or Trial SDK, shall materially comply with the Specifications (as applicable to the Subscription selected by mag+ Customer and as applicable to the SDK and/or Trial SDK in the Order), for the term of validity of the respective license under this Agreement. In the event of any material non-conformity with the Specifications of the Software, SDK or Trial SDK as applicable to the Subscription, or license in question, mag+ shall, at its discretion, repair or replace such defective Software, SDK or Trial SDK. This warranty expressly excludes any errors arising from improper use, viruses, external factors, and mag+ Customer’s failure to install prior Updates, in the event the Software, SDK, or Trial SDK has been modified or altered in any manner or if the error arises as a result of the combination of the Software, SDK and/or Trial SDK with any other software or hardware, and in connection with any device which itself embodies technical limitations or deviations from the Target Devices. Any Apps derived from the Software, SDK, Trial SDK, and/or Deliverables may contain bugs and/or may not be approved by third parties (e.g. without limitation, Marketplace(s)) for distribution. mag+ Customer shall, itself, be fully responsible for final testing of any such Apps and clearing the same for commercial release in connection with the respective Marketplace and Target Device(s). mag+ shall bear no liability of any kind in connection with any decisions made by any third party (e.g., Marketplace(s)) or for any changes made by any such third party in connection with a Target Device or the technical specifications thereof. Any and all Hosting services facilitated by mag+ shall be handled by mag+’s current Hosting vendor and shall be subject to such vendor’s terms and conditions. mag+ makes no warranties or representations as to such Hosting vendor’s service.
                        <br/><br/>8.3 Unless stated expressly otherwise in this section, the software, SDK, trial SDK, documentation, support, subscriptions, updates and upgrades of any kind, and deliverables are provided without warranty of any kind, whether express, implied, statutory, or otherwise. mag+ specifically disclaim all implied warranties of merchantability, non-infringement, and fitness for a particular purpose.
                        <br/><br/>8.4 The warranty disclaimers in this section are material, bargained for basis of the agreement, and have been relied upon in determining the consideration to be paid under this agreement and in the decision by each party to enter into this agreement.
                        <br/><br/>8.5 Should mag+ Customer desire to obtain a higher level of liability coverage, license usage, extended warranty, support, and/or service level, mag+ Customer shall contact mag+ with a specific request in writing, and mag+ shall reply with a quote for such additional mag+ undertakings.
                        <br/><br/>8.6 mag+ Customer understands and agrees mag+ has no responsibility or liability for the deletion or failure to store any content and/or for other communications maintained or transmitted through the Software or any services related thereto. mag+ Customer further acknowledges mag+ Customer is solely responsible for properly configuring all services contemplated herein, for taking steps to maintain appropriate security, and for backing up content and Apps.
                     </p>   
                     <p>
                        <strong>9. LIMITATION OF LIABILITY</strong>
                        TO THE EXTENT PERMITTED BY APPLICABLE LAW, mag+ DISCLAIMS ALL LIABILITY FOR ANY LOSS, COST OR DAMAGE, INCLUDING WITHOUT LIMITATION INDIRECT, SPECIAL, CONSEQUENTIAL, OR INCIDENTAL DAMAGES, INCLUDING ANY LOST PROFITS OR LOST SAVINGS, LOSS OF GOODWILL, BUSINESS INTERRUPTION, WORK STOPPAGE, LOSS OF DATA, OR COMPUTER FAILURE, DAMAGE OR MALFUNCTION, OR FOR ANY CLAIM BY ANY PARTY, EVEN IF MAG+ HAS BEEN APPRISED OF THE POSSIBILITY OF SUCH DAMAGES, AND REGARDLESS OF THE THEORY (INCLUDING CONTRACT, TORT, STRICT LIABILITY, NEGLIGENCE OR OTHERWISE) UPON WHICH SUCH CLAIM IS BASED. IN NO EVENT SHALL MAG+’S TOTAL LIABILITY TO CUSTOMER FOR ALL DAMAGES NOT EXCEED THE AMOUNT PAID BY CUSTOMER DURING THE ONE (1) YEAR PERIOD IMMEDIATELY PRECEDING THE CLAIM IN QUESTION UNDER THIS AGREEMENT. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF THE ABOVE-STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE. MAG+ AND CUSTOMER ACKNOWLEDGE AND AGREE THAT THESE LIMITATIONS ARE AN ESSENTIAL ELEMENT OF THIS AGREEMENT AND THAT THE PRICE FOR THE LICENSED SOFTWARE IS DETERMINED IN PART BY TAKING INTO ACCOUNT THE EXISTENCE OF THESE LIMITATIONS.
                     </p>   
                     <p>
                        <strong>10. INDEMNIFICATION</strong>
                        10.1 mag+ Customer, at its expense, shall indemnify mag+ against all losses, damages, claims, expenses (including attorney’s fees and court costs) arising out of or resulting from (a) any use of the Licensed Software by mag+ Customer (unless and only to the extent the loss is attributable to a breach by mag+ of any obligation under this Agreement), (b) any breach by Mag + Customer of this Agreement, or (c) any actions by mag+ Customer Parties or Persons that would constitute a breach of this Agreement if that mag+ Customer Party were a party to this Agreement and its obligations were substantially the same as mag+ Customer ‘s obligations. 10.2 mag+ Customer shall indemnify mag+ for all collection costs (including, without limitation, legal fees, interest, penalties) incurred in connection with collecting any and all overdue mag+ Customer payments.
                     </p>   
                     <p>
                         <strong>11. FORCE MAJUERE</strong>
                         mag+ shall not be liable for damages and mag+ Customer shall not have the right to terminate this Agreement for any delay or default in delivery of the Licensed Software resulting directly or indirectly from acts of nature, forces or causes beyond its reasonable control including, but not limited to: internet failures, network failures, computer equipment failures, telecommunications equipment failures, other equipment failures, electrical power failures, acts of God, terrorist action, acts of civil or military authority, government actions, fires, epidemics, riots, wars, sabotage, insurrections, labour shortages or disputes.
                     </p>   
                     <p>
                        <strong>12. THIRD PARTY</strong>
                        12.1 mag+ software, and, as applicable, SDK or Trial SDK uses external third pary source code libraries. mag+ has reviewed such license agreements and determined that mag+ is permitted to have used such open source code (to the extent such code has been used) and to sublicense the same to mag+ Customer (to the extent such code is sublicensed to mag+ Customer). With this said, it is mag+ Customer’s obligation to review and accept the terms of such open source and/or third party software license terms. mag+, in furnishing your company with this information, aims to comply with mag+’s notification obligations under such open source licenses. To access the updated list of Open Source Notice / Third Party Software Specification, visit – https://support.magplus.com/hc/en-us/articles/203808498-reference-open-source-notice-third-party-software-specification subject to change by mag+ from time to time.
                        <br/><br/>12.2 mag+ is entitled to sign this agreement on behalf of third party and does not assume any legal obligations of any kind in connection with such third party or the third party Services. mag+ shall invoice mag+ Customer for the third party Services, collect such fees from mag+ Customer, and remit amounts to such third party as agreed between third party and mag+. Any claims by mag+ Customer against any Third Party’s shall have no bearing on the Agreement between mag+ Customer and mag+
                     </p>   
                     <p>
                         <strong>13. PROMOTION</strong>
                         mag+ shall, immediately after the Effective Date, have the right to release a public statement disclosing the existence of this Agreement, and to use any and all mag+ Customer trademarks and logos in connection therewith. Further, mag+ shall be permitted to display the covers of mag+ Customer’s Apps on any of mag+’s websites as well as in any and all other media in connection with the promotion of the Software. mag+ Customer hereby grants mag+ all necessary IPR rights necessary to give full effect to this Section.
                     </p>   
                     <p>
                         <strong>14. CLIENT LOGINS</strong>
                        14.1 mag+ reserves the right to access mag+ Customer’s login, Customer Data and the Plugin features used by Customer solely for the purpose of further improving and updating its Software and Services.
                        <br/><br/>14.2 mag+ shall ensure that such access to customer data shall not amount to any breach under General Data Protection Regulations (GDPR).
                     </p>   

                     <p>
                         <strong>15. VIOLATION OF THIS EULA</strong>
                         mag+ reserves all rights not specifically granted to mag+ Customer above. mag+ will have the right to proceed against mag+ Customer in the event that mag+ Customer infringe against mag+’s rights. Any use not within the precise scope of the license set forth herein will be considered an infringement. mag+ Customer acknowledge and agree that mag+’s damages in the event of your violation of this EULA will be substantial and that mag+ will suffer irreparable harm in such event. As such, mag+ shall have the right to obtain equitable remedies, including but not limited to recovery of damages, obtaining injunctions, recovering statutory damages, recovering attorney fees, and any other available legal remedy.
                     </p>   
                     <p>
                        <strong>16. AUDIT</strong>
                        16.1 During the term of this Agreement, mag+ may require mag+ Customer to provide the addresses of all locations where the Licensed Software is installed.
                        <br/><br/>16.2 During the term of this Agreement and for one (1) year thereafter, mag+ or its designated agent may inspect the Licensed Software and mag+ Customer’s facilities and records to verify mag+ Customer’s compliance with this Agreement. Any such inspection will take place only during mag+ Customer’s normal business hours and upon no less than ten (10) days prior written notice from mag+. mag+ will give mag+ Customer written notice of any non-compliance, and mag+ Customer will have fifteen (15) days from the date of this notice to make payment to mag+ for the applicable units of the Licensed Software. If the shortfall in the amount payable by mag+ Customer exceeds five Percent (5%) of the total amount contemplated by this Agreement, mag+ Customer will also pay mag+ for the cost of such inspection. Upon request by mag+, Customer will provide to mag+ via e-mail copies of any and all data files related to mag+ Customer’s use of the Licensed Software, including all copies of the Licensed Software or provide mag+ with remote access to such data files on Customer’s computer system.
                     </p>   
                     <p>
                         <strong>17. TERM & TERMINATION</strong>
                         17.1 This Agreement shall come into force upon the Effective Date. This agreement is subject to a lock-in Period of 12 months starting from the Effective date.
                         <br/><br/>17.2 For License Subscription with One Time Fees, the Agreement shall commence from the Effective date and shall conclude after a period of 12 months from the Effective date
                         <br/><br/>17.3 Subscriptions and any add-on services or support (unless clearly identified, in writing, as having only one time fees) run for an initial period of one (1) year and automatically renew for periods of one (1) year at a time unless either party submits termination notice to the other, in writing, within thirty (30) calendar days prior to the conclusion of the initial term of the Subscription (or ongoing service or support) or any annual extension thereafter
                         <br/><br/>17.4 In case mag+ Customer terminates or causes breach of any term of the agreement during the lock in period, in that event mag+ Customer shall pay to mag+ the entire subscription amount for the remaining lock in period
                         <br/><br/>17.5 It is further provided that in case of termination of this agreement prior to the above mentioned lock-in period, shall not amount to refund of any payments received in the form of Initial setup cost, advance and (or) subscription amount received from the customer under this agreement.
                         <br/><br/>17.6 This Agreement shall remain in force after the locking period unless terminated in accordance with Clause 16 or any other provision of this Agreement
                         <br/><br/>17.7 In case either party should become bankrupt or insolvent, the other party shall have the right to terminate this Agreement with immediate effect
                         <br/><br/>17.8 mag+ shall have the right to suspend access to mag+ Publish portal of mag+ Customer or terminate mag+ Customer’s license, if mag+Customer materially breaches this Agreement (including without limitation failure to pay any and all applicable fees and fails to cure the breach within thirty (30) days of receiving mag+ notice of the breach.

                     </p>   
                     <p>
                         <strong>18. Effects of Termination</strong>
                         18.1 The life span of App(s) will be until this Agreement has been in force. This implies that after the end of the termination period of Subscription for the respective App, mag+ Publish portal will no longer be accessible for the App(s) or the brand administrator.
                         <br/><br/>18.2 Upon termination, pursuant to section 17 above, all mag+ Customer’s rights in respect of Software, SDK, Trial SDK, Deliverables, and Documentation shall cease and mag+ Customer shall promptly, completely, and irrevocably purge and otherwise destroy any and all copies of the same. To clarify, however, should mag+ Customer have licensed the Trial SDK but opt not to license the SDK during or before the termination of the Trial SDK term, all mag+ Customer’s rights in respect of the Trial SDK shall immediately cease and any and all results of the use of the Trial SDK as well as the Trial SDK itself shall be purged and/or otherwise destroyed.
                         <br/><br/>18.3 All Apps released via Marketplace(s) shall remain in full force and effect and continue to be available to mag+ Customer’s customers for purchase during the termination notice period. To further clarify, should mag+ Customer desire to cancel the SDK license but nevertheless retain its license to one or more Software Subscriptions set forth in the Order, mag+ Customer shall maintain a license to the SDK version existing at the time of such SDK cancellation free-of-charge; provided such SDK use shall be strictly limited to the terms of this Agreement, shall exclude any and all rights to Updates and/or Upgrades of any kind to the SDK, and shall automatically terminate when mag+ Customer ceases from having a valid Software Subscription.
                         <br/><br/>18.4 The foregoing rights of termination are in addition to all other rights and remedies provided in this Agreement or at law, subject to the express limitations set forth in Section 8 and 9 (Warranty Disclaimer and Limitation of Liability).
                         <br/><br/>18.5 Provisions contained in this Agreement that are clearly expressed or by their sense and context are intended to survive the expiration or termination of this Agreement, shall so survive the expiration or termination hereof
                     </p>

                     <p>
                         <strong>19. WAIVER</strong>
                         No breach of any provision of this Agreement shall be waived except with the express written consent of the party not in breach. The waiver by either party of any term or condition of this Agreement shall not be deemed to constitute a continuing waiver.
                     </p>   
                     <p>
                         <strong>20. AMENDMENT</strong>
                         Mag + has the sole discretion to amend or update Terms of this Agreement at any time. Any amendments shall be effective on the posting of an updated version at <a href="https://www.magplus.com/legal/eula/" class="text-link">https://www.magplus.com/legal/eula/</a>
                     </p>   
                     <p>
                         <strong>21. ENTIRE AGREEMENT</strong>
                         This Agreement contains the entire agreement between the parties on the subject matter of this Agreement, and supersedes all memoranda, representations, undertakings, and agreements, whether oral or written, previously made between the parties with respect to the subject matter of this Agreement
                     </p>   
                     <p>
                         <strong>22. SEVERABLITY</strong>
                         In the event any provision of this Agreement is deemed by a court or tribunal of competent jurisdiction to be unenforceable, such provision(s) shall be limited or eliminated to the extent necessary so this Agreement shall otherwise stay in full force and effect.
                     </p>   
                     <p>
                         <strong>23. NOTICES</strong>
                         Any notice given under or in relation to this Agreement must be in writing, signed by or on behalf of the party giving it, and addressed to the relevant Mag + entity, “Attention Legal Department”, at the corresponding address, or to mag+ Customer at the contact information mag+ Customer provided when purchasing or registering for the Mag + Products. Notices will be considered delivered when received if delivered by hand with receipt; the next Business Day after sending it by pre-paid, nationally-recognized, overnight air courier with tracking capabilities; or five (5) Business Days after being sent by registered or certified airmail, return receipt required, postage prepaid, to the address mentioned above.
                     </p>   
                     <p>
                         <strong>24. RELATIONSHIP BETWEEN THE PARTIES</strong>
                         No relationship of principal to agent, master to servant, employer to employee and franchiser to franchisee, partnership, or joint venture is established between the parties. Neither party has the authority to bind the other or to incur any obligation on its behalf
                     </p>   
                     <p>
                         <strong>25. GDPR</strong>
                         <b>25.1 The EU General Data Protection Regulation (GDPR) comes into force on 25 May 2018 affecting all organizations processing personal data, and bringing new obligations on data controllers and data processors. Article 28 of the GDPR adds a requirement upon controllers (the organization who determines the purposes and manner in which personal data is processed) to ensure that certain provisions are included in contracts where there is personal data being passed from one party as the controller of that data to another acting as a processor of that personal data. The aim of the Article is to ensure that a controller of data who passes personal data to the processor controls how that processor can use that data.</b>
                         <br/><br/><b>25.2 To give effect to this Article processing of any personal data by a processor shall be governed in accordance with the articles of GDPR.</b>

                     </p>   
                     <p>
                         <strong>26. U.S. GOVERNMENT RESTRICTED RIGHTS</strong>
                        26.1 All mag+ products and documentation are commercial in nature. The Software, SDK, Trial SDK, Deliverables, and Documentation are “Commercial Items”, as that term is defined in 48 C.F.R. §2.101, consisting of “Commercial Computer Software” and “Commercial Computer Software Documentation”, as such terms are defined in 48 C.F.R. §252.227-7014(a)(5) and 48 C.F.R. §252.227-7014(a)(1), and used in 48 C.F.R. §12.212 and 48 C.F.R. 227.7202, as applicable. Consistent with 48 C.F.R. §12.212, 48 C.F.R. §252.227-7015, 48 C.F.R. §227.7202 through 227.7202-4, 48 C.F.R. §52.227-14, and other relevant sections of the Code of Federal Regulations, as applicable, mag+’s computer software and computer software documentation are licensed to United States Government end users with only those rights as granted to all other end users, according to the terms and conditions contained in this EULA.
                        <br/><br/>26.2 In the event the Uniform Computer Information Transactions Act, any version thereof, a similar law or any other statutes implied for Internet transactions (collectively “UCITA”) is enacted as part of the law of any applicable state of the United States or any applicable country or any applicable region within any country, such statute shall not govern any aspect of this EULA, any license granted hereunder, nor any of the parties’ rights and/or obligations arising pursuant to this EULA. This EULA and the parties’ rights and obligations arising hereunder shall be governed according to the Governing Law provisions in of this EULA.
                     </p>   
                     <p>
                         <strong>27. GOVERNING LAW</strong>
                         This Agreement shall be governed by the substantive laws of the New York, giving no effect to any conflict of law’s provisions. Any dispute shall be finally settled by arbitration in New York, United States in accordance with the rules of the American Arbitration Association. The United Nations Convention on the International Sale of Goods is expressly excluded from this Agreement
                     </p>   
                     <p>
                         <strong>28. DISPUTES</strong>
                         This Agreement will be subject to and construed in accordance with the laws of the State of New York, excluding its rules regarding conflicts of law. Customer agrees that any claim or dispute it may have against mag+ must be resolved exclusively by a state or federal court located in New York. You agree to submit to the personal jurisdiction of the courts located in New York for the purpose of litigating all such claims or disputes.
                     </p>   
                    <p>
                        <strong>29. ASSIGNMENT</strong>
                        Neither party may assign this Agreement in whole or part to anyone without the other party’s prior, written consent. Any attempt to assign, transfer, or subcontract any of the rights, duties, or obligations of this Agreement without such required consent is void unless stated otherwise in this Agreement. Notwithstanding the foregoing, mag+ shall be entitled to assign this Agreement to any company (i) owned or controlled, directly or indirectly, by mag+ or (ii) which owns or controls, directly or indirectly, mag+ or (iii) which, is, directly or indirectly, under common ownership with mag+ (iv) in the event of any change of control of mag+
                    </p>        
                    <p>
                        <strong>30. RELATIONSHIP BETWEEN PARTIES</strong>
                        No relationship of principal to agent, master to servant, employer to employee, franchiser to franchisee, partnership, or joint venture is established between the parties. Neither party has the authority to bind the other or to incur any obligation on its behalf.
                    </p>        
                    <p>
                        <strong>31. CAPTIONS; CONSTRUCTION</strong>
                        The paragraph headings in this Agreement are for reference purposes only and should not in any way affect the meaning or interpretations of this Agreement. The word “including” is intended to be illustrative and includes the meaning, “including, but not limited to.” The singular of a defined term includes the plural and vice versa.
                    </p>        
                    <p><strong style=" text-align: center;">APPENDIX-A<br/>PROFESSIONAL SERVICES</strong></p>        
                    <p>
                        <strong>1. Services and Obligations of mag+</strong>
                        During the Term of the Agreement, mag+ shall put forth commercially reasonable efforts to produce, on a non-exclusive basis, the Deliverables expressly agreed to in writing between the Parties. mag+ shall not bear any liability for failing to deliver any items not expressly agreed to in writing. In the event of any inconsistency between this Appendix A and any writing agreed to between the parties hereto concerning Professional Services, the terms of this Appendix A shall prevail. To clarify, Professional Services shall include, without limitation, Creative Work, Development, Managed App Submission(s), Managed App Update(s), Managed App Update Add On(s), Managed Issue Update(s), Private Support Screenshares, On boarding, Training and any other Professional Services undertaken by mag+ at any time during the term of this Agreement.
                    </p>        
                    <p>
                        <strong>2. Obligations of mag+ Customer</strong>
                        2.1 In consideration of the production of the Deliverables, mag+ Customer shall remit timely payment(s) to mag+ pursuant to Section 7 of this Agreement. 2.2 mag+ Customer agrees to either accept or provide written reasons for the reasonable rejection of any Deliverable(s), in whole or in part, within fourteen (14) calendar days of mag+ Customer’s receipt of such Deliverable(s). In the absence of any such acceptance or rejection during the time period stated in this Section
                        <br/><br/>2.2, the respective Deliverable(s) shall be deemed accepted. In the event mag+ Customer rejects any Deliverable(s) pursuant to this Section 2.2, mag+ shall put forth reasonable commercial efforts to correct subject Deliverable(s). mag+ Customer understands that mag+ Customer shall only be permitted to reject Deliverable(s) based on such Deliverable(s) failure, in a material respect, to conform to speciﬁcations which have been agreed to in writing.
                        2.3 mag+ Customer shall, at its own expense, assist mag+ to the extent reasonably necessary for mag+ to perform its obligations under this Agreement. To clarify, mag+ Customer shall provide all information, documentation, contact persons, instructions, and any other cooperation or assistance necessary for mag+ to perform its obligations under this Agreement. Should mag+ Customer breach its obligation under this Section 2.3 causing delays or additional work (including, but not limited to, its failure to make timely decisions, to participate in meetings, and/or to otherwise carry out its reasonable responsibilities contemplated hereunder), mag+ shall not bear any liability in relation thereto. In addition to the foregoing, mag+ shall be entitled to charge additional fees and be reimbursed for any related costs resulting therefrom. In the event of any changes to the Professional Services requested by mag+ Customer, such changes shall be subject to mag+ written acceptance thereof, and mag+ shall be entitled to reasonably adjust mag+ fees and the delivery timetable at issue. Further, mag+ shall be reimbursed for any of its reasonable expenses relating to such change(s). mag+ shall have the right to refuse to perform any Services which mag+ believes will not conform to the timetable, cost-structure, quality standards or necessary third party technical or legal requirements related to the Agreement.
                    </p>        
                    <p>
                        <strong>3. Fees, allowances, and payment</strong>
                        For the production of the Deliverables and for any other Professional Services, mag+ Customer shall pay to mag+, the fees set forth in the Order (or as otherwise agreed, in writing, in connection with subsequent Professional Service assignments) and such fees shall be paid in accordance with the Order and Section 7 of the Agreement
                    </p>        
                    <p>
                        <strong>4. Termination of Professional Services</strong>
                        mag+ Customer must provide thirty (30) calendar days written notice of termination of any Professional Service work previously ordered, and mag+ shall be permitted to invoice for all work (including the work of its Independent Contractors) performed up to the effective date of termination. To clarify, mag+ shall be entitled to remuneration (for itself and its Independent Contractors) at the rate that would have otherwise been billed during the thirty (30) day notice period had no such notice of termination been received.
                    </p>        
                </div>    
            </div>            
        </section>    
    </div>  
	

<?php
get_footer();
